app-template:
  controllers:
    radarr:
      containers:
        radarr:
          image:
            repository: ghcr.io/hotio/radarr
            tag: release-6.1.1.10360
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi

  service:
    radarr:
      controller: radarr
      ports:
        http:
          port: 7878

  ingress:
    radarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: radarr.hl.mathielo.com
          paths:
            - path: /
              service:
                identifier: radarr
                port: http
      tls:
        - hosts:
            - radarr.hl.mathielo.com
          secretName: radarr-hl-tls

  persistence:
    config:
      suffix: config
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      storageClass: local-path
      globalMounts:
        - path: /config
    media:
      type: persistentVolumeClaim
      existingClaim: media-data
      globalMounts:
        - path: /media
