app-template:
  controllers:
    radarr:
      containers:
        radarr:
          image:
            repository: ghcr.io/hotio/radarr
            tag: latest
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Amsterdam
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

  service:
    radarr:
      controller: radarr
      ports:
        http:
          port: 7878

  ingress:
    radarr:
      className: nginx
      hosts:
        - host: radarr.hl
          paths:
            - path: /
              service:
                identifier: radarr
                port: http

  persistence:
    config:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      storageClass: local-path
      globalMounts:
        - path: /config
    media:
      type: persistentVolumeClaim
      existingClaim: media-data
      globalMounts:
        - path: /media
