#ENC[AES256_GCM,data:ZXWAkksAybhTMsD0Y+W7jJMSkbV8gVMgnP915X24Vcwr5pP8grTPzpEDya2eZEOdjUCV2+lXswjdBhs+PGt/jc3ZRAmLFXhhTC/TA3wCxpu0lQ==,iv:Hwm5VYNTlh1aPDgZSW8J+VUqljHRYNoyiP5Y/B7X/nw=,tag:O5aaDtZTdbj/k3f4AbHUXw==,type:comment]
#ENC[AES256_GCM,data:Yqp7feDi8UlnnLjzFztSyAdjXfYstvy76dMawbJG2qC3QI45gALedYYcbZ1BioMP+YI9q1cFFpewWPnq6TzvS4xP5wBwzaYYyt4+HU4I,iv:AOefu7gcsGSG7uQ5ZmC2/32zo18y9Tch9uBPYoobGlo=,tag:gIv84jCrgUH474cRZepmew==,type:comment]
#ENC[AES256_GCM,data:aSrXi9unHMF1oZhrRQU1iJ5Y3EH8klf/a72WtSJyWjNPPHeVRu5kQdmsWyHy/IPNHoU7rVue0qKQIKnWJ4xAPDibWfiAEsMd5bL9,iv:5whVy0Fkk8IZU8GQdKbHH67oC5Cxy8FgVk5oHaziP1k=,tag:Oh/8skmGJIH13VzEbFfOcg==,type:comment]
ansible_password: ENC[AES256_GCM,data:+pITeB7CYkU=,iv:ufdYvKItF7hZWDwAKhwgyyodLJr0O2XS+KogZGxkVgM=,tag:/tTpCI06O434DGzTRdsjVA==,type:str]
#ENC[AES256_GCM,data:bB9sCvzLm7KOiWbokBm1roNMqO2mExcgTEjE4Khz+sVRSdf7JXNZRXTpzjwaSibtddTG4rbL6e4DS1w0IHlgOUrynsrANn9iL20tnGjBUsBMImM=,iv:r7p9US+hxZJTgJllyOK9JF9HG4WRH+S/Kabq4bKfKwk=,tag:DAmfrClGT5MWkg8JfhtG7Q==,type:comment]
ansible_become_password: ENC[AES256_GCM,data:F7vC/5RBqkfItZjY8N+xVzpeBGVwhQ==,iv:CJE0lkpM7VnQ/U4kcRh+eVTZN9/S1R7aG4Mcmgel2so=,tag:Vy0P0KjLz3o8xTbB5nvSgw==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNWw0eVpCWEt1SjQ4emQw
            N0xHc2xoS2txVjAzQWJhNXhkSy9oVWhKaWk0ClJ4ZGVycnBpUnIveVZMeVgrbTY3
            QjRXSXFDemZxWWRFYVVpY1NML3JHUDQKLS0tIG1xNXlKeGNBR0lOcUptUnAzdU5D
            R0tCSExwR2lrdlAzQVZRdVNxWTl3MG8KIFBO4EeTB5sjM8/q0SIh4r0JXKxH1ehi
            Eypki1VOmiYWLUbLn0bUVIk/MMhaYumVEW1S7DQ0RxhnwXzhQoVe/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJemF0dm1mMWNMNUJTWmp5
            STFmOFc1b2E1bC95MG9DRlA5T05HS2EyT2pvCkdoTmlYSkUvbllWRURGL0U5bTNw
            SGcyWHZna2NyREdnbW5LcFpKUFJqWjgKLS0tIHlsc1UrbHZscjgxdWVRa0RkRWlO
            MGtQbVhrcHNtT2hldGg2RnBvcVFCUDAKUs89bzFrQKRZng8VLE1DH3LsrUBTG7FQ
            JauYIvRUtMRC7IKods51SHbmksYc/67V4MxxCOZOZNNim9c8sBedLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:58:31Z"
    mac: ENC[AES256_GCM,data:nwHhu9kMeqaiJ6ttv4I/THtPFiYlI81Ggs6HXXP1JbfOdTYr7zbRiI8WrHy2Be5gtOKFd4E3pYoVYb79Lpouo1CU5F+ugcrQjKEfQgHiRb7RTm3hvP8Z0qwCCaJicUPHE71v6exJgrM96BYabgU9FnKdAXs0sdk000qISmk06/w=,iv:YrgjzRMN2KwUK3aRJy8dfXuiyIeVMlCXaH5pTQIx1C4=,tag:BvpNNRctWEx0xK32Uo/qQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
