#ENC[AES256_GCM,data:3k4opdUfbydhG8B+8e+DqTd8hWaANs/D8uLu0tXhqXaiCXauHrYqAg5LTGhXWGFYspoWKPQ8StlSWYCCqNYiXPStse073K2PIAGKIW5pSs0=,iv:UiBfNQIrZItx3ORVPZ6ymqJtHO1kMi5OdrbdkwXNrW4=,tag:mZlufa5R+sdr/PoACk7/8Q==,type:comment]
#ENC[AES256_GCM,data:6ZW4XL9pUlnQZfTgvdwkGawBapxrKu65AwtQ8lFnq2E5H8Gi/rOfM8arMd1ak6NRamQsaXBwE3j+7dc=,iv:B8dkrIwdm/KJVAX51NLjK5BZpnGizwq/dj4EqD9xknI=,tag:hBi3S67aBL3sF3SCfnsysg==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:a4+sYbLOwScV5+AvYDe8SqLLCRlB3zkw/gckyeqDed3TT0KYwufrkC5VKmdqkP62VJ2BRePKIKMFXQQt/g==,iv:6aHrsvrrx1v6m3BrWdnEFHzJbHLMhKN5wlPKBtsZnhw=,tag:VXkHQuJEDv+Gl32/k2igyA==,type:str]
#ENC[AES256_GCM,data:LyELaog2DXwTqN9x31Zh9DCjL0uRZM2FcwtDEo13Qbb9FXD3O2qjA5dYIe/xLTgeF3HOElMswA==,iv:dNexlMjmMpVF8tKeHJABD0v42T7CkMY1yGIhmKziCRk=,tag:nL613NZ5S6rXQtLJf7//lg==,type:comment]
pihole_password: ENC[AES256_GCM,data:zdtF1qz5KWLjkVSPq8Vpo9p6U94XeQnW9sWc3Oreblw0NiQV,iv:huUHwhtBQhA5TGrT/d2SQuGJv+zK8YdbCEmxkx92PmQ=,tag:Qy2JXiJbFAiRjb6858DpXg==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R3J6S28xMjhsU0lCM2ZR
            ZkNWSE5CZnZVVzFhbUsyZStqMEZMbDdCZG1zCnJRQWZNWUJ0VDlrY1N1S3ZBT0ZU
            VzdzQlRGZldlMVA5TmtRNjM4WlgwdHMKLS0tIFZyNGZFVjBiL3llSitDYUZKeDNu
            bE5mYjVvbVhlY3lQK3FTT0NpS29aSlUK1kk9jSZzOMzqFn/inCyUHepYiTEnPkXm
            CS7B0/IVbTzvxsQLodroCe2i98A3XqpxpgABzPBapRP2V0+25PP8oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T10:01:50Z"
    mac: ENC[AES256_GCM,data:t9FOzD+uTMaS/9/N9wqO5Z4Y8VUzG7ThaM6Y4Mer99TtBGRRscQKzM7AKbSxRYIdOyu2Qpd80KqmAPzEu/nwrtbqnAvnxOIdd/yj2zBReOYd7Y7pH7Ds0M7XVRFiFEuT+EsO1Wxyi0JA08T4Y+DYlIbtMlub4KRzG0AuNt8/tpk=,iv:LGv3paFshniGthHPRYXCxB0TdMyMH31NFHTjYXzCOgM=,tag:5Q/gA+bIa7wnHRFKx+skBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
