---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgres-lh
  namespace: tools
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
