app-template:
    controllers:
        main:
            initContainers:
                gluetun:
                    env:
                        WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ebA1tk97fFFe9ywqszhUdcCxMBKiJxlQAYuvyrDc59FIlRdwS2n/kBWjCtE=,iv:Hw2Jq+1XKiU/4o+xnRENzF9oDP89P4RSX0lgulANWBg=,tag:D+Dyfg7eu3lVQJiSIB0zFw==,type:str]
                        WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:TozBjV5gad3IwMw=,iv:vYC0a+EhlNeJ8D4hrbnfZz0kuNg92zoXkma2N9NVE9w=,tag:C5NkTOMgdVVND8/9IeFjnw==,type:str]
            containers:
                mam:
                    env:
                        #ENC[AES256_GCM,data:YmiyuFu2+KffGKx0Ig3UGdzTyi5fJFAFe9alWCce9q/mOKvtu8ZEyLkKB7BpyNgq5sQPjMNxxqptC903csOQC5D8I+g=,iv:hA8oI68KKvlVOCzvUU+eSHt18Z3VoJKu5Bysx3u8GTg=,tag:Dnd9hulpe8+w3gInr8Kqow==,type:comment]
                        #ENC[AES256_GCM,data:+GDuIxlqPhyPfKw073om/hAztHNRHvxBPWC4SN8K,iv:CEl3rVTwQinja5AFEuBMt2nfDkzgjpcC8z2uf4TCxgY=,tag:2lAeeqpaz6zqEtIn3R1cBw==,type:comment]
                        #ENC[AES256_GCM,data:/vy1bcmxzmuPgB2tmWZPjc/ZPsV53azxvtYQzNWirYmr3WpOygUyDxXIdaMmXeyRP42xuwqErktzCEq81q+4hJ0=,iv:KvIN9fwk/emWBXe0q8+2Ffyz2Zfm6E9DDwREERjM3Ik=,tag:gdpBeUmU5bbPgWeVGw8txA==,type:comment]
                        MAM_ID: ENC[AES256_GCM,data:EL3THvED5E5jmkKp2tK2/7uBSacwUR5nfMZhNdsYGTFzWktM1TSPizO4qprSg7htNrdgHWlLF27gFSfGnbXC//UtxxkB1At+mZ5Atwyna5Ckycm7S4emixwd3hvOGNt3uG5AZeR8FcMPsx1S/0ZqZRcou3RZngdspUCtFKEWopaIf7GGToDuHALPT2kLaoQ3wkcefsGsAXM3AmsFdCpYi6EWsifls/+xY+8aS9UG1Ym2XiaZpZAatviw5JpYkpAXAUFmq0n7S15C2hKfhAIm07nZVV3obht2qib71v7ghSSBm9dAjJamgIYHnDF6sx1+VzvBhlLbPWIntHtQG54fG2m2ybjZN5EB+8rMJdHKF9p+4upgTNdB+/rT5mP0QxB8SaAPdA==,iv:RZ1xM17vqvbNvQgadkHF0lFlcrb5h/4R7VQiVZhBpog=,tag:B5tH4s+Kmrgj8tCQVIOaNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRmNua2Rsd0I5RjZySXVE
            K09jaTBnU0J1SlRqZHFMam9wemc1NjBvcVJFCmNkaWhGVTNDZURDQURXRVlpQ3Y1
            TTRBcE1FeHozV010SkdpRUZLNGExVjAKLS0tIGlkdU81SzY1RGRIbG9GT1VOaUwr
            aFFiSE5FWTF6NGk2QUMwUTJ3RDBCN0kKScdD3Th0vuYu+H3LcmO2gZUHWGKLelHb
            /pB1tKHS9pF8SxIxR/mfkOz0RyUHHx+G7Kg/4OOiojSywZV2Wb26KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYU5ZNGpteUFXYmRIeSsr
            ODYvaEZ2aEZPWTZPSStYSUJNYWpxaTF5V1hVCnJVMi81SnhXcVRGZ3BUL0QvclVw
            blA0Q0w4NnYvRE5hYWF0WjFMUmFWd3cKLS0tIE9ib1ROSWRiejBNR09vYlB1azhh
            NktaTHEzQlFUb29FMXVCL1JvdTZUSG8KmOCgBx0HwN3ti8nt81WnALxEpoRXiz9t
            KTM1iAArwT7CLdtJOZFe8ZmX5y14uPshoUe9MYFoPXJFhWaYXh2pLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
    lastmodified: "2026-08-28T10:08:46Z"
    mac: ENC[AES256_GCM,data:t5ic4MUZuBoj7mWxSvmSKV1T61w0h1C2rbLtgYzKb0FlsGrbT9X6qPF2Q4zwQJAQjJif0zrnAXfr+h08wKO4wLGVHkDZ+I7SdsYLrG1C5V0xdZMM0GK5Mi6eX+HLZeueCbEEspF9rNzN3brHLXs3TsXtJqcOYiXuughuw2pCT0U=,iv:L9IP/Zjw+UnbTK/hPAM1LeM+xMpXf9aN9LOCTUnpKZ0=,tag:GHpP+BgofTFOoOfflhx1dA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
