app-template:
    controllers:
        main:
            initContainers:
                gluetun:
                    env:
                        #ENC[AES256_GCM,data:En1bNLC69g==,iv:1mO4BNKlXDVgfVC0O3MEVhJ5RCCINCaQ64RThdVJjGc=,tag:gA4BmZNnVgXNtpypTmKtOA==,type:comment]
                        WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:D13D7vafqfiavFofwbYIhbN/k4earUrbNDo3RT/ji2kXiWyvzDPIQBMwooc=,iv:H76jrmCgpqfLKgUZnuXw4YyT2/n26qweiRVO04hmD1M=,tag:lrqEn4Qrn2kywEQ7cHrtJQ==,type:str]
                        WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:evNzml1bLBOWMtc=,iv:ycJlie31uhm9yiLCYP2gUT1UnrmKIAF2zkYfPXY7Bkg=,tag:CIYZJkvauj6NkhI1mvc4qQ==,type:str]
            containers:
                mam:
                    env:
                        MAM_ID: ENC[AES256_GCM,data:lUr6PrO8gGWbGjYgODDYETRtjZD67tQdPGgK6yW2JqSxV+WMPox2oVxxcBzEybBOK1HWCNByQtAIcq6ELKzZQ+k73sgW8qIjcEpDr8GS6qIBgMulbtzhHbgu8mzHv9RrHRDWsS10Q3FLSOrup8/olXzVsI/Y16WrkMo8Um9SUiMqfxzdvs4BM/ym2MVYOJEA1OpEYJ7E8XtftM4AjTYd+yGLXz+YRd1UYmzcNXhLx5qqtTpIfrB7fFOsy7d1C8uJixpTCoP0JB4soT/WdDBYcY8ZepwPX/+q02X7jNQDfawy/zYrJb5KhOXWkCvGCwGUADJddQn9VetahU+eR4YeCe5hIw40WOY0IIv1cTDHtcdOjWP7/3nW1RNPoT/tgL8lR+vN7g==,iv:my4vUeJZlcpevUHB4w1fDmPMz4Rpty/vPRvdBeJvg8Y=,tag:1bw2qrwc6DZ3HH6vN2yA1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieXpQSHgwWlIrblRlQ1Fv
            eWhnMnllT2R5YVhCeW92dzgrT1BpZllXZFVrCmlDZ0h4SHZQSmJsSUlLS296eU1t
            eUdHcDJpMkVtU3VrWTBZWm4yTE5OUE0KLS0tIDZjUGlMbzZUNUlBbHZHeHNXMTRL
            czFsWTBMV1ZxQUdKTE9rVlZNL25JOWMK/ZDwZK+vCz6gxRMq03UMwosFJgANHcX/
            lqwj7/kgHKn6G9iYlR2Aq6MII+fBMoLsFEx3YnDyEF5pla5HHzh/pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTHVFY1V0ZTV6M3Bmckc4
            RnVLdTZZelc4bURmUlN1SDZtQVNhZms0bmlnCi9KSW9lTXgxQWZmbE9XdFIydVQw
            cWsxRmdzNzFjSzFTZVJkdURCUjREQzgKLS0tIGhJdmVMU3pVMkFjMndTQUR4bzNy
            elhEZFMvZ1p4bFhkNTBBZy9FekZmRncKoOWCTZjG1Vdj+X1hoEqUuY1RzZWxaus0
            pc2/rttln7XLZ61s+8ZElHJTTjbSG2l1JFGmdgoEOHxpWcGVvp9seQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
    lastmodified: "2026-06-04T06:50:12Z"
    mac: ENC[AES256_GCM,data:Z95rrbpFzC8QrL2nb6tCmYuoD5pq4oG3P2QsN+Wr4dtGVvW0oyI3MmvpPXH6nErJ2/0c7OWciZQMAnK7kt7VWMsAwlEf9NUH+mgTwyQZUIILytcSGhNpYOwsJ3w9WcmXC/Qe7zEgnQ5L/2fbOWdG8t+JdseUL1bS/0/xM8CjPFU=,iv:6H1f3McVTN5N83BU6YaS8YNTm0jVRQXw+fav+0tXXvE=,tag:ArOLGteea7V7D4mqBTd8tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
