app-template:
  controllers:
    pulsarr:
      containers:
        pulsarr:
          image:
            repository: lakker/pulsarr
            tag: 1.1.6
          env:
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi

  service:
    pulsarr:
      controller: pulsarr
      ports:
        http:
          port: 3003

  ingress:
    pulsarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: pulsarr.m6o.dev
          paths:
            - path: /
              service:
                identifier: pulsarr
                port: http
      tls:
        - hosts:
            - pulsarr.m6o.dev
          secretName: pulsarr-tls

  persistence:
    data:
      existingClaim: pulsarr-data-lh
      globalMounts:
        - path: /app/data
