app-template:
    secrets:
        core-keeper:
            stringData:
                GAME_ID: ENC[AES256_GCM,data:ljTHiDVsQe3M0hzKn3lkJ7aOwjSDeOU/evLHkg==,iv:q6+LRuXXQ3IP6CJl98DP5yn3ayCyYOa3p5PDGumxVXk=,tag:Z+zLUJgEIUd1EIrpU4zNKQ==,type:str]
                PASSWORD: ENC[AES256_GCM,data:sUdsVw==,iv:2//Jf5IPF/9cYPnBppe8+889jahxJtNjFdXBZKeLATM=,tag:f5dmdDy3LJUrR0ltv25fQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa1NhVUlTb2FSN2NVS3Vs
            R01zM2J2cE9VNEk2NThtV1BhSXlkbDg2cTBzCmU5MG5BU3NaSWRwOWlpYk5LL0FN
            OUhxNDZIOEhUYU1GamFqVkJ1ek1Fb2sKLS0tIFBtUUlkSElCdVZOa3VBcnRoUlNh
            Sk53TkdZMU01M21mTng3cGdYL0kxNFUKk/Q7l3dpApGVU/CnCOd1Q/tlbVIjtvRk
            Z9w/yNbw97EMsVTnrS1tDJE+5KAR7CcchTMS446MyFqBb2BRjuq4Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV3dZRE1TN2plT1VWOGtp
            d2V6R3AxSGtzcklzaHlSK0xWQS90MGJBR2hBCnFwUmNxT2dNTG1JMlNMdVNyWkRt
            YjVWMzFuL1E3WTRVM2NDdGs2dEF2Z0EKLS0tIDBwOWFCT0xhcDVkRUVJOVBSSncr
            NDhaVGJqSjU0VlIyMUluN2RKclB6SW8KMMWJk1BfHPEL/TV6wzC7EjHruk+o4AQl
            9OVY2Hqng4G9ASX2dxefLIQEbG9ppEunIVVsB3LQrHEc08qJua17+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
    lastmodified: "2026-09-14T05:02:39Z"
    mac: ENC[AES256_GCM,data:B6654o2L/+aQHB7ZqI10hmLr/9bxAyWu/fpWbR0beLoK3ItzwqdSncburBTziaGQ3v2q/AMjkHNqqLCjRgEqHLPfynotcGGWAmCwmV6z5UHYykkTnPZWaWb6wt40WwU0wIJPUfC93YOAuSxBpAvoKpENe2+iXqibjL7MjrgGqe4=,iv:l414lB9OI6RsBotlHZV/s4RcC+Dg9RStGWeEysV8/NE=,tag:wyVvw/sM3OcGKMCRy3mH+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
