controller:
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 128Mi

speaker:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  frr:
    enabled: false
