apiVersion: v2
name: searcharr
description: Telegram bot for Sonarr/Radarr search and add
version: 1.0.0
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: "5.*"
