app-template:
    configMaps:
        config:
            data:
                settings.py: ENC[AES256_GCM,data:fjO7s/NaSlVkLGBugNF+DmMKp6T8PKKbixSnOK/2+pwRe2PQUD60JAlr/glA/SkZK7aXL7ezFtVm7tXre60RRzmaTFlAPy1ux0SXibupSPuohwOqIYBrJj9CbZio/vVdbcqNyzmpYCdvkKaMXxJAu5sebLQw+VLAU9pdOuaRq+6OwEhR+metPVx9HHLY/CEMfadkjok0X/EAnIVndhH4x96rWbBbivinBfJuaJpHunMZqMEOQju+oMAALmx4RQL8hrQiikOgD2cgSpGINrKAyOhG25EWOsU7OyxxBZwjlk4jx7SHDhVEeMBTEf05dJiZCTxVyWj+mANSvZ8bUQ8Jes8iyfgzt2z42+YR47cWU3jcZjRLG28tAj0om9DTNhoTFC5zjyWl7PyiG8EGNK/9koGqNiyD7sq6Y03FFaxuh8hS1Hx0tiLrQCQUerBmlg3eDk6Go7fkEmgP7wdhFhKZN4+QQYxzY/MICuKj+oR1OkRO2PtcUqmvpf/Z+HwLz3eGwR9NdrYOwzLIhhx5ZnTPzG4MQh0/7jMi2LfksDuVe9g90QH67eztOhGzwxqDavembl6BCHdvVspOqA35Ju+Ybmev+I+YIted30Gz+bx/wjbnWakwZe191CLi4s9ve4XcCy8MMH3rcZGMWmFEuHyheabWhOjrqBUCQgco52fjlcRcY+PmM21iRItSq5cQT9DKsmolveJ3OnOiMCRJtGvIPW77piZDz4tcBHj2Hiuxm7AK2/ZZrjXPRaPevBDLAHVXhUfk+kj08/HzKUMeBb8n7W6ICYiAQW5wfv/vwnT6WAwyjRYzYv9xHGYnBMvddxumZkMwxyKlqKh46cw3tz5WQvmWK9IKsdVdtS1bxJyDXTLxkvJ24jjSMvOu0kiDuombiqGLMsgB/NlX58NtMvS1tGGaQRhkKg71oNEO6iCA3ZTPBoznwGpNcLkhGe/mncqmXNh+DAljXUwWCSvw9LrPR9sgvNRDfGxnA+5+ebxHLfhP9vxTa+/3fd5pkK23sSAQ9cMEaVeJW8SfTyhgVENYaZOlLfb75nrd7MbmvC+DG3p4DYer3FdK8DwiPIkKXfXA/Ffpvzji6yTxGW9YAz2O1IEQaHJ2qHh2XkWvTphFG2mjq3QjHxmGyihKOoy617h+8yxvWktNk22sI3fCX8l9FCkJq+Dy+IW5fuQSrxwGYFzqHnXo3CWH+9R6ZIKRiQeKK3RzmL6d3Fkv/DKeZaFk13J50KfVApCMLvwGFxN0GlXtcDc11zBC/KGK5+FOoeWf7uuYt7QWlZLYdgeQHNR+YAxeN5AU18d91tHNVxDrfxHBthmIguYHqDCo0DjSdqbBS91dXvbD9cx7hDVW084ZfoBpCFJd3YqMNjitySiXWrPgzfWDtVUg/DGBAHMLH7IwLVsSGW/WAfC7zL/hwvcqFMs2j6kvF6NHyt9p7t1poMQnDFRdIB/8TA90H3gAhGxGn0BbVGmdV2dGbyPbUQrljvx3agWQ/ta5o+NDFn9VSWF9V9RdBH0ADcjACFo=,iv:mOIqiidYx1k+l9niagfytXZLl58Gm8QB2/8wzbwsdNg=,tag:sn4CsMYtwBd/bCW6U+MveA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY0RlT2ladlhCcmlYaDg5
            dWIzNWlkZEpWTTQ5NEh6Q1V5RVo5T2dvMGkwCnEvWjY5YUtPcHV4eHFYTDNYdFJo
            U1V6ejVmcVRpVFpNelM1cjlJMnlmaGcKLS0tIEkzWkhnc3crVlYwOWl2NzVmMzRY
            aWxHMzBjM3c1T01kcmRPdGUxZytJbkEKm0ZRbSOr3bg7qvjuFmKSzuFs1L9ptDx7
            Jg5nrgfm81b+O1QVUpZgZLNS2IbdxvUQUT9SYmFpB5ulzdB8r+ylKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NVRzRmZSdUFDdFpsRlFj
            VFQ2cllJTXZCSG1hQzNaUEJXeHRhUWdBZUE0CllqOVlobWpvSkFQME5SWlNGbWdj
            dnNkdVFaL0xFY09obDMyaVFwVi9raTQKLS0tIHl2K2lacS9WM0JNWSt3SktTTUp3
            WHA3aS9WWkdrMXZpQ3hYbFRRQktnNUEKDSNEDpLvymrlks4R1co0jY7CGqagQ2ML
            AWJ5ciSLXEIn/ZIL/Kv+osUJV4IeSVQ79gSuQpeegasGHakAwGGXPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
    lastmodified: "2026-06-05T13:59:49Z"
    mac: ENC[AES256_GCM,data:q9w6jdIXotBhoFL3BN1ilptlWSn9SHiAc/JP/bj3cjN3/gZpB+RqQZACFlkR/XVt1fam+JJgb687dtvMURSFG5IG0XNPkbaKLWzy2rbizCc5tGTcVmrWxMRORFACufuu66iASK7WLRRwQ0mUDNgVms8px7+cUzKK33aT0S5QAEA=,iv:m8Fnqh7h4zQUL2wuOzTTmaeNqHU2bK6Jqnx8fPtcIpg=,tag:aHINivPC0sAmgF3hQmksgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
