---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbt-se
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:mathielo/homelab.git
    targetRevision: main
    path: k3s/apps/media/qbt
    helm:
      releaseName: qbt-se
      valueFiles:
        - values-common.yaml
        - values-se.yaml
        - secrets://values-se.sops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
