apiVersion: v2
name: prometheus
description: Prometheus metrics server + Alertmanager
version: 1.0.0
dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: "29.23.0"
