app-template:
  controllers:
    sonarr:
      containers:
        sonarr:
          image:
            repository: ghcr.io/hotio/sonarr
            tag: release-3.0.10.1567
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi

  service:
    sonarr:
      controller: sonarr
      ports:
        http:
          port: 8989

  ingress:
    sonarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: sonarr.hl.mathielo.com
          paths:
            - path: /
              service:
                identifier: sonarr
                port: http
      tls:
        - hosts:
            - sonarr.hl.mathielo.com
          secretName: sonarr-hl-tls

  persistence:
    config:
      suffix: config
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      storageClass: local-path
      globalMounts:
        - path: /config
    media:
      type: persistentVolumeClaim
      existingClaim: media-data
      globalMounts:
        - path: /media
