app-template:
  controllers:
    bazarr:
      containers:
        bazarr:
          image:
            repository: ghcr.io/hotio/bazarr
            tag: release-1.5.6
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

  service:
    bazarr:
      controller: bazarr
      ports:
        http:
          port: 6767

  ingress:
    bazarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: bazarr.hl.mathielo.com
          paths:
            - path: /
              service:
                identifier: bazarr
                port: http
      tls:
        - hosts:
            - bazarr.hl.mathielo.com
          secretName: bazarr-hl-tls

  persistence:
    config:
      existingClaim: bazarr-config-lh
      globalMounts:
        - path: /config
    media:
      type: persistentVolumeClaim
      existingClaim: media-data
      globalMounts:
        - path: /media
