#ENC[AES256_GCM,data:3k4opdUfbydhG8B+8e+DqTd8hWaANs/D8uLu0tXhqXaiCXauHrYqAg5LTGhXWGFYspoWKPQ8StlSWYCCqNYiXPStse073K2PIAGKIW5pSs0=,iv:UiBfNQIrZItx3ORVPZ6ymqJtHO1kMi5OdrbdkwXNrW4=,tag:mZlufa5R+sdr/PoACk7/8Q==,type:comment]
#ENC[AES256_GCM,data:6ZW4XL9pUlnQZfTgvdwkGawBapxrKu65AwtQ8lFnq2E5H8Gi/rOfM8arMd1ak6NRamQsaXBwE3j+7dc=,iv:B8dkrIwdm/KJVAX51NLjK5BZpnGizwq/dj4EqD9xknI=,tag:hBi3S67aBL3sF3SCfnsysg==,type:comment]
TAILSCALE_AUTH_KEY: ENC[AES256_GCM,data:EEf5anBffhi5cy3XZrL4XCd4PnOKgSqUssMFNwFzzFqZ/Nvd/L661Pi5OizNl2r5Gfn/FWZtBsaxPEEscA==,iv:pdnFJHW4w1tipb9iJKHsywhCMvTbRWLE2ssBB5GOuvQ=,tag:snztg6IcVjtrKhe8MI5/UA==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R3J6S28xMjhsU0lCM2ZR
            ZkNWSE5CZnZVVzFhbUsyZStqMEZMbDdCZG1zCnJRQWZNWUJ0VDlrY1N1S3ZBT0ZU
            VzdzQlRGZldlMVA5TmtRNjM4WlgwdHMKLS0tIFZyNGZFVjBiL3llSitDYUZKeDNu
            bE5mYjVvbVhlY3lQK3FTT0NpS29aSlUK1kk9jSZzOMzqFn/inCyUHepYiTEnPkXm
            CS7B0/IVbTzvxsQLodroCe2i98A3XqpxpgABzPBapRP2V0+25PP8oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T08:40:10Z"
    mac: ENC[AES256_GCM,data:tCCBoCaKqbNlb6xeEl2omY2pt63F6KwAstISjphOiUohwKJiVW+VJrHCKXOf1NS+1GiLkXc+0HubwH7X8Big0tuHelVNsTri6q66h6USzaQYw1+CTF3r8cfW2Ci6+wjyBVtdu6azrA48IYSxUti2GaEydBxqpZDRaZ7uLrq91ss=,iv:iIZMPSAoffWeeGU59mHWPlkkAo4BXFJjXGagqqlNyJ8=,tag:zW8L/iVrUu3hoEZTr8YqUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
