app-template:
    controllers:
        plex:
            containers:
                plex:
                    env: null
#ENC[AES256_GCM,data:UPWLkN1PdhmxaRYH3BgngjQUHsgNO7o8p/mPOPXlNdEj0Cd9GANtRbbv49qn,iv:3NSQSeopQmA5pCXkfXELdYf8faeiCyjpZKAtS+ecXDQ=,tag:cNxaR5LKIs2N6kLta8wlPw==,type:comment]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS2dyMXVsbDNLV0ZtWGpF
            aUxSZGtwSi9RZ3UvT3pkbFEzZnBQeDFjc2hNCjJvbktUNHRiSDcvQ0loaGwvdDhu
            bUx0NDdTdzZ1Q0JWRUJRUDdNbzB3SjQKLS0tIGpnUE1Wb0tJTFZQdVBEMEU1VU0y
            TFlxOVRiWnFheVJCbFdTbHhzaWFYQzQKB1OaFlTmQoDXDmxh4VcUNdylNz526Snt
            EDpz+2goy6rTy/hjjdCyx6++uJp/AvO9F59AuElKmmxsciZLC0rCSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV3p6SWVqN25TNUdTSUx3
            TDI2VlBvY1FndXlDV3lRcmVBMTkwS0o1UmlvClczQldXMUpBRE51ajhiay82eHJJ
            cE1zRE1NbEtZR3ZBaXhMNEZnbndyRnMKLS0tIHNFVTVmL2hUM1pIUlc1KzBHblBY
            WGVUT2diclRKTVJNcWNGamU5cmphM0UKKzUYWmifLXDAgcneXz3zK002BEgZNEfe
            ka2RuGoBMCZyhF6kc1BQgwYWCFGuZgQSF8itOJLHLKdU5qhGn7q4Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T06:38:02Z"
    mac: ENC[AES256_GCM,data:TRmKpSlCXXqhP0+QQkIoff+JPb5wwTORTS7Y/QoDtVZvNoGt9aPceeyQJ0U3UFt82uDokUfWMefHreiVogDh49VR7CGT2DEm+fh5ZIEA9sJPrtjtwecXtuTSjESJN9oD0X70fHjICJaXlXl0p7tkhf+8SvpxWtJik6ytpmqC7ZY=,iv:fajHJXzIW7K09fyQp1/X+BXKgCPrEo6hTPunX4WhFMg=,tag:zVjpPZjd2IGBOfyCl2CYkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
