[k3s_servers]
k3s-srv-01 ansible_host=10.10.50.3

[k3s_servers:vars]
ansible_python_interpreter=/usr/bin/python3

[pihole]
pihole ansible_host=10.10.53.53

[pihole:vars]
ansible_python_interpreter=/usr/bin/python3
