[k3s_server]
k3s-server ansible_host=10.10.50.10

[k3s_agents]
k3s-node-01 ansible_host=10.10.50.11

[k3s_nodes:children]
k3s_server
k3s_agents

[k3s_nodes:vars]
ansible_python_interpreter=/usr/bin/python3

[pihole]
pihole ansible_host=10.10.53.53

[pihole:vars]
ansible_python_interpreter=/usr/bin/python3
