adminPassword: "admin"

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.kube-extra.svc.cluster.local
        isDefault: true
        access: proxy
      - name: Loki
        type: loki
        url: http://loki.kube-extra.svc.cluster.local:3100
        access: proxy

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi
