app-template:
    controllers:
        qbittorrent:
            initContainers:
                gluetun:
                    env:
                        WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:D/tI0sYgkqLAu1hvGsQbbDinJMitvBB+Y+K6lt+/FfTXjYZaTo0zyrn8wfg=,iv:4VPV90mQjf7l5biBrh50JH5+i2jfzUdfRrkwI0h7fY4=,tag:9psDb2DIDH1bv+uKBw+NfQ==,type:str]
                        WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:iri8ZXaBH6uGATk=,iv:68JQCf4dR0sP9XtpWG3uPanHDqEgXZmP8sZYVoI/GsM=,tag:3y9qC8wGTQtMmo1tYCLJDQ==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqelFsTWp1STR3UnAwMExG
            QitxbFE2d003ODJMcHhMZ2FiWEsrN1NpTXhRCkh3QUxLOTdmVmhtRTZKNW1jY2pk
            VzNkS2VsTFkxR0pMeDRPaWxNMks1dXMKLS0tIDFUbTlURGhHczRuTUZnOUp6NWky
            MEliNzY4ckloMjVjdEtocWVydzVSYlUK0dyRa5253CgJFnUioklYbZAwILCYS8Z+
            GKeQizQWBJNtfQbxNbyxh7hjX2YmBUBLgMpyp7XkJu9i3ouwnIsMzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSFJTaXVPYldJVkVLRUFK
            UjlwZU5kVW1FLzNud2l4SzdseFJUQk8vS25ZClY5RnFNVnYxeFhNS0dTQVV2QjZV
            dURNekIwMWRCdVg1VEtvdm0yNFg2SFkKLS0tIFlDdWlBQW9LRys0bWd0L3hyR2R5
            cmRyY3VDTENWNEZiZGZOaVM5Unp0R3MK0AVM/aeiXDJbvgjewsjlI96EFw6cN+qa
            CjymPy7f8hoXc0NGI0K8FAGMVMhwt7ac9gMu3Fy4M6B/yPHxGDb/Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T17:19:16Z"
    mac: ENC[AES256_GCM,data:B1MIGuO3sAXr+F7/JbUK832heNkAMn1bafaZV57hpaNltgD9oYFQsVRdzn92oL8QZVM31L2akPYK8TdWBswZ2AfdfvlMkfAwLNAHd0ny+upTYQjJMQ8Cq43vUo4qYU8MIiSwCONEW5ZSULomTSMiFsYzNnzSN1JueJ6nTvKDkGU=,iv:JPLvWeE6/UHV5r+9apCBwEkF+mHX2JP7ZayCZp3ZUrc=,tag:3NRKtxsIHU1D/Kxzsy8P0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
