app-template:
    controllers:
        qbittorrent:
            initContainers:
                gluetun:
                    env:
                        WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:UgZhup/sNXdrxIXqJbR5Pv6kSX4gyU0FgPLrqMWD0VxhA1/2TkZZXhDC5P0=,iv:/4UbQVZcsECNYUfWsTQ82o6uTe6OgPKeDdmJTr3SqNk=,tag:cRs8v6vjNWZHYww9tYHzCw==,type:str]
                        WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:iri8ZXaBH6uGATk=,iv:68JQCf4dR0sP9XtpWG3uPanHDqEgXZmP8sZYVoI/GsM=,tag:3y9qC8wGTQtMmo1tYCLJDQ==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqelFsTWp1STR3UnAwMExG
            QitxbFE2d003ODJMcHhMZ2FiWEsrN1NpTXhRCkh3QUxLOTdmVmhtRTZKNW1jY2pk
            VzNkS2VsTFkxR0pMeDRPaWxNMks1dXMKLS0tIDFUbTlURGhHczRuTUZnOUp6NWky
            MEliNzY4ckloMjVjdEtocWVydzVSYlUK0dyRa5253CgJFnUioklYbZAwILCYS8Z+
            GKeQizQWBJNtfQbxNbyxh7hjX2YmBUBLgMpyp7XkJu9i3ouwnIsMzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSFJTaXVPYldJVkVLRUFK
            UjlwZU5kVW1FLzNud2l4SzdseFJUQk8vS25ZClY5RnFNVnYxeFhNS0dTQVV2QjZV
            dURNekIwMWRCdVg1VEtvdm0yNFg2SFkKLS0tIFlDdWlBQW9LRys0bWd0L3hyR2R5
            cmRyY3VDTENWNEZiZGZOaVM5Unp0R3MK0AVM/aeiXDJbvgjewsjlI96EFw6cN+qa
            CjymPy7f8hoXc0NGI0K8FAGMVMhwt7ac9gMu3Fy4M6B/yPHxGDb/Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:08:35Z"
    mac: ENC[AES256_GCM,data:ya7+8U+CG30OY7CoG3e1/FYieY28lq+A6kUfk1aPppLTk3ZNRfmX1G8tw/XXl3fPi01kv1NtAx9Ec/ubzG5Y9/IdOS6iNr3/uZefMtfW82ce5df3NmBxpHap4gfFI3P2Eo0bdC43o6QYkAlrzE2Ynb4fyt6q2bAm6Gqr6UWY49s=,iv:keDWbKg7LsF3aBiZF2DoSqx93TILDvSsgp1SvW4wMhw=,tag:QclfxmBVROthlFohcW6fYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
