app-template:
    secrets:
        sure:
            stringData:
                SECRET_KEY_BASE: ENC[AES256_GCM,data:LL8VStH4zRsWBWsDlXFRkKWN6V24SDTT7IO+ejG1lyCjBzmIZNibUASsowpoGz8GfIjQ+QNYEFmUcKK1YcHJ4AWz6/EXTZBMcBVVebWjHo/lEeEGUrMbgs0Egq5lDQ2/c5prP514NmGK53H45rKaFFU2AKRl1RXmbLxEjfPJdiQ=,iv:u1Gde/ZUOsB6FUZ32fb9TKp8Lsx/lCOaeVJmfn3f8o0=,tag:Hr9ANveCJuKFe5fk8V2jsA==,type:str]
                POSTGRES_PASSWORD: ENC[AES256_GCM,data:afemVZaJ9pt4B/d8UfLq0tu2KASz6uIPso10xrYYyUHtJrmz,iv:mL2Scz4F+6TRkcQ/SBN+GabrbrR91YS1SG2Iqm3BIP4=,tag:uQgNnZ85LXfFmwez1jfVIg==,type:str]
                ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:/b+MpUdOWNkc9+zd6BQqFd1A2wb8v+kxuOmJHySQQcg=,iv:dGDdrKY2mglrn/mEx/W3TWbys/pgKL/o1j0uhir12SQ=,tag:c/skQGTCRQTWyYgt1FDIgw==,type:str]
                ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:iC3NRSP0NBXdNcBfaGmg0HevVIFT06IpE/xdWv5jG08=,iv:FR0uL8C15Q1n9ewoitjNbYUNobz4gR6SLtOgFrqc6Ks=,tag:1bhLiGeslyQ5tJ5ZWSAjoA==,type:str]
                ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:IAEbKk5dn5nbEqZ7tvrYlH7en26Crmf5K+HOWpJWtCY=,iv:ZlgJ7+EXhav429j98qSeDSBOTjTPutRxEHpXsR6Zlc4=,tag:QibEow3noFzx14D1dIj8+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZTZ2cFlnRzRaTzRwNG1U
            cGpEYTNiRVo3NCtKNUZzclNiTjhDa1ltV0NzCjByeFJHZXM0QmhCdkI3eEtWaHpm
            aCt6RVU1YklpNUhUMDFHWG5FN1ZNVFEKLS0tIGt3czdtRUh2QUdCTGhVZXEyRktN
            M0prMFF5TkhDc3QweVE5S043MVZka3cKhEXl6z8sIDAaJi/l2X3sf7zwnowPg1zh
            QcIAS+5WAOd7mm/A1G2+8ckI5aLG6fEhfw13SfoTF3su14GJlpSbJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUkFGRG41REdDNmlZLyt2
            MlVNRCtsV1FuQmx4SzN3WUhaNjdSMjNZUEZZCmJUUDRVektSZC90dXZBUzNiNmJF
            d0lJWjV6QmhnQWtmYUVJRnVqM2ZraDgKLS0tIGNTODN2SjBaV3c1MDFQQ2tIVUhT
            dlJwYS9McFo1VmlreElHS0VURGVnbTAKhnUMldf/VjkTNZzNKzas94eeoyYriayX
            7nEgbuqnoWQLHD63SnpNpP1cs06IayCVkr4S1GJFallgTBb4EmW7uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
    lastmodified: "2026-07-05T14:02:51Z"
    mac: ENC[AES256_GCM,data:bv3sP0M/ck1o2nkaFJB01WnLzhQcjiRNAkkoen68afVT9O0gtrRrYQDERUwMhHV1Ds8lGHcXhU7cshiaFczB7kvLIsjgQRxqcvqVyqLUkSpYGqlpsE4ayAH+nw+PmjByWtoSp/AHwzPlkv86mEIviuFDbUM/kRoOWmW9++IJULU=,iv:YO5mGBYxwFhZDrk/Egs03Wk3R9fjC78GTaXmqR09Lhw=,tag:9spLzzXlJoplQlGyjufkVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
