app-template:
  controllers:
    autobrr:
      containers:
        autobrr:
          image:
            repository: ghcr.io/autobrr/autobrr
            tag: v1.76.0
          env:
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

  service:
    autobrr:
      controller: autobrr
      ports:
        http:
          port: 7474

  ingress:
    autobrr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: autobrr.hl.mathielo.com
          paths:
            - path: /
              service:
                identifier: autobrr
                port: http
      tls:
        - hosts:
            - autobrr.hl.mathielo.com
          secretName: autobrr-hl-tls

  persistence:
    config:
      existingClaim: autobrr-config-lh
      globalMounts:
        - path: /config
