app-template:
  controllers:
    prismarr:
      containers:
        prismarr:
          image:
            repository: shoshuo/prismarr
            tag: 1.2.0
          env:
            TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

  service:
    prismarr:
      controller: prismarr
      ports:
        http:
          port: 7070

  ingress:
    prismarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: prismarr.m6o.dev
          paths:
            - path: /
              service:
                identifier: prismarr
                port: http
      tls:
        - hosts:
            - prismarr.m6o.dev
          secretName: prismarr-tls

  persistence:
    data:
      existingClaim: prismarr-config-lh
      globalMounts:
        - path: /var/www/html/var/data
