app-template:
    controllers:
        sabnzbd:
            initContainers:
                gluetun:
                    env:
                        WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:a7B3BuN2qwUGP/fwPYe58dX5Ohb8QJWeNYDK3vk02SooyIDXXB1+LLsC9uQ=,iv:ZTL3TtOOGT+XlazTl5N9KgDE0CxXpN0db2NsuG4YaPk=,tag:5jdO3XRBjtVdexTqUXrcVw==,type:str]
                        WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Kq4Vm4gAbv3yFuc=,iv:1kcvBWVjxo/ZmR6kxHl7V6qT0uTMi3b/ctfpx7bImu8=,tag:dpO5w8+B+yjcOEkKQAPdUA==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWklaOUtKS0FyN2FnalFz
            M0tVbUN2S1E0WGM3b0xmQkUzT3JMSFozaEJZCnlHYkpNYlFZdkIxdkpaNjlUNkdE
            cDlUamtGRWNTN0ptNGNLREVvcFgvb0kKLS0tIEhtY2dtMnAwVEo0WlZWRzFUUFJ4
            cUxNQlFWcHVXNlJYa3BxNkNRUWxiVTQKdaIAPkPpVuL3ElzPy3H4DXGZmy0/Kv+C
            HjutXbvIl6XiMz1j0+Drd8JhlN7I89NLe7ouzFXI/rZUZ8Slke0h2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R000dzNkMytVNk1JT1dl
            bitJV3RmRUpBakk4YW0xRGlsbkN4YzA3L1dZCm9LRzVzWDhVZm9YNnNHbFNIOVdy
            dGNFMWxhQWczUDFHUEkxb2VRT0ZyQW8KLS0tIFNBTnR0NUtmVXFyY3lZOWtXbGNl
            ZXR6Q004QU5aQncrcEU1SDJsVEltRVEKSm7crTfYNwhQc5xbeA2ZipqFpXsEgzkr
            Fm5hRcMfBMqjPfluMqKMAvoPltyLO8sBGazOZw1uWBK4K5FuT9yBbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T06:36:54Z"
    mac: ENC[AES256_GCM,data:YF7AZieZQtbCbZZtbkA7BfbpeXunZRLuOx/ABRPxbg/GW7HGWad8bNgNQMxkbrWrgHAnjgnsK4dme72WcJEDoT8izdU8yYU0p65YPc8b+LNwiCfT0s6nYN23q5kid83JRweVWjpmlsXNTxi7GB10CH2HAGx3NpTQzMWyxbKTW/8=,iv:9Uko25F1Lc45K5Ee75L8kQrpt8ovsPLTW0H5jiTMs4Q=,tag:TC6FZ7Mh9pbgPXdZqpiLlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
