#ENC[AES256_GCM,data:GL0DvLhdDOAVA0NJoEGfb98uLKsPHHj3mCJ5DABQaxX38MoSnAy2Sc+X,iv:0c1xe6h6DNm26e3oYYUX8oGXIwIpu2GBWyY5ElUos60=,tag:fJwLdWA2zJPn0+Ju+G/IbA==,type:comment]
github_ssh_private_key: ENC[AES256_GCM,data:BHun631OI1prwXxUgluOMJ2256WDjz+BRvAhRoarxJrmIWlGuvCuITjSTNYQ7IAYgkQGa+n70rAO/YEGe3T1qI7j39lc49u7CPUZrCyh8yVDQOXFWvntAfYwWeObegLaFKe/5+bHRXNN17gUc8KBUCZ8WBfSqwshLzH9Fnq/PconjTRLl1FNKlAa4IfLX1+lqqVVI0pP785GpNJVGvaUrq3jVUCKLxm6Eclvq1uSnMaSYP9gg6thqdAEwhTDFYJ+vZsLQTeN/K10k7Yw7KaJB5tWGwG4L+ZO52pb6Ctb4R0yzyYAum2upGszNhwH/bS2Uf55GmlrM29URn7eUUqO5F6f+BPtTaAilv/We5jkDu6xt7LmvEACB3+89+f+0eM412qeXcpZh8+KDNSoNWEd0x51SEqzDKNgAKlVJ2YTQEru0ERX+29eSgWulMcFQLXx+lI7KbWILJk7IFzXBhkbj9ohHxZp6qpFnB22jeCU71g5jJ2n24m01DuqB7rFOhWx/B9G,iv:OvhKMJ/gwMhydTiJrmxYwkT5PWhoUt4olPT2vEUEYDE=,tag:4bB+ik/b3owhhgJ2O+qSsA==,type:str]
#ENC[AES256_GCM,data:aiu9dohtT4r8HP7xm5LxqSTycaSienhRrkyh7xGhtMIZatDjOTPB0V6Kpck=,iv:Fgff6foLbBeZU8Cjsy+tW+eeo31Px8pI1QTs9ymx6ug=,tag:YHaVnTOh6MrNGRnV6pVdBA==,type:comment]
argocd_admin_password_hash: ENC[AES256_GCM,data:Y5IFHhgFfky4X2C+3ZLIEwYgUtpm4fWwkdzYX+2GDKeIikmRfkV/pFWH0DCLjdavXWJgX8Siy6RVwqvHgg==,iv:2NBfWdzroJ1m5OyHJFyOZafXPrBGH5n7h83yarQuiHs=,tag:M9emEkxdmZ4fiWsEUCZEaw==,type:str]
#ENC[AES256_GCM,data:ahx+IhmOuCAdV0GP4DpLwbvsLJCuUpz+JODTZrfTx8Gt9DzqB4z+2cX0ZQ==,iv:5fhpRyDDKklO+DWqTPEGwEgkgrVYwAh6z5VqUpuGRoA=,tag:YG2KPyq5BZbYypmgIFhacw==,type:comment]
sops_age_private_key: ENC[AES256_GCM,data:KAsBlyDrAdRiNOonpT0APp84ZPewrngiWKvu5QhalkeTOAbM7RHS55dHNGxd5jreUKQGzTsWPxJSV/5A+Jhwa6Pj52taHu46uqE=,iv:BmMb0h68K0JPhuNopVIniL0hfft1EP0/fnLYvP57KRk=,tag:hnM968VGKd4fEUH15+BWmw==,type:str]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTWs3Zm14M3hoZy9ETUpT
            MTJPM2x1YTlENkNCYUM3SmYrSm04TmJ0MVR3Ck5UWExxb1dGSDFQZDF0NWw2cGhG
            eG41ZDFZaHpCYkdIMjNxUzZYNFpHMzgKLS0tIDYxSG9vTXVJOHROZCtPWndjQ0tV
            SkllVzFFaDBlQ056UHhCYzNYd1gySjQKhrQ2rSiJheFVc7kMPLbxxQYrwH7hWpMK
            uWkYVsRsDAYsHsP5exGKzDNt42pvxm5jbLi1s/USs60IdKBlhFBWPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaEo0UUl6b1BuUW5jREZM
            ZGw0YlRtOVJqdUxsUXZPTy9mNVpWWDV5L1c0CjMrVmRqQ1hQTWhiL1dNdTNtNjlI
            bkE4dkpaLzRKZFFiWGNYY09sellsS28KLS0tIElWTHJWQlRSdnFzQ0hWblNtL0V2
            MzBpMnpQNjZCMVhsbkc2NDBhNzBYdjQKoV6l/kodp/hSd1g5MXRgggHRk2dKivdy
            QguJ3uW10feH42l/XwHv0p87Rl1c4JxOuua+jCHaL8sdBCBZeGqOAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:33:08Z"
    mac: ENC[AES256_GCM,data:C4zflpafRZrNdi8iQ4ZLxuB4ltN/M0KDIb2FD92EtNXeBo0ov8qwCguTpjFB4HpJI4CYuTufYXzdcTW57/R7p2b3/mxqWA0beXh0jnMw/bV/dw01g9WyR+6A7vC2IIlGrAZA8i2e7z/RSoXF5s/s7+HHo+uTqMEt+NOLISnpDtI=,iv:Idb22IzvJqenLe/mELNMQTCYUvZqD7vppf+YfV1vksE=,tag:uan4kByAjuTTU0Kmae3eVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
