#ENC[AES256_GCM,data:QIb7lbwMRMk=,iv:DhATM34ZYTQwDC61sJcokGMvzjAATFsNNiI9wkYB6NM=,tag:IfQ2fLKaHeYRpR1Fed9cwg==,type:comment]
grafana_admin_user: ENC[AES256_GCM,data:dgzKCGbbbYE=,iv:yX6RTkbhiMCWwRxf8uvMwvr0jO7MErrRk/z2SawazeM=,tag:zjN8grLEL2ta5kdIoaPtGQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:0MGwDoZZf+WUoCyfTHwV2JxvHyuGnqqvljFRgNrTB2Va69+o,iv:wZ5zma1TaHPZnSypN7yZHlX1epWqB2+19fs9Nn4HrrA=,tag:aZu7z031RjirI7rvU7XNnQ==,type:str]
#ENC[AES256_GCM,data:3iM6w3hdsBi8/w3b5q+IBgPb,iv:CiuxKAtCvV0E0SXdgfwfvnFVoOjG9mmR60DoHoGK/Tc=,tag:rjd7AdJm672j4VtNeKMGjg==,type:comment]
telegram_bot_token: ENC[AES256_GCM,data:x/zy1QAlvsPFZD/t4tUgM2rvre3sCwlnVelcSgknt7rM7g+CxYo4LZLIEXjw7A==,iv:xskzevy5HoBE7EBXRgh5qrmP0GzagJi/yYpnE1pH0wU=,tag:vnapU/+al8MsR5yGQyygJw==,type:str]
telegram_chat_id: ENC[AES256_GCM,data:P9ONaxjj2Ssh4qo=,iv:/aQpjF3uQw9GLl6V1x2YYxM01RMt7DozpGS/VWOAGSY=,tag:PLJUlEobmG4K3G2mXccUVQ==,type:int]
sops:
    age:
        - recipient: age1gyywmz5ypukdr265ltj45s3vtnckyvd7qn5ddr8qepj8ktdzsers20cz6t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RmFSb2RxNlQ1dnFreVJq
            NS9GT05VVlh3UkRlZE1XVnJmS2E2b24rWW5RClhoWEhlVFZUb2M1cHNnNnI0R3I5
            TWh0eE1mVW1MLytXbS9GODRtbU03dm8KLS0tIFAwNnBhOFRkRjlEdE5UZnlWTzhR
            TklCeXNmMi8raGJvbkxzRFMxQXQvTGMKLnEH6XBVGpGJdhynigA5ta+MXcw4ronm
            LZ5NHEs7aIgt9weP87S3CQBTyCFxjZv6MVEcNuZHxJuQmtXmbchFTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kt5aynyagn4t6v4epgl95ls9gpskq49f07j2v797g99zhje8teussmnytu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUElUd2doL3JWR3Q4Y3FM
            VTRYNVZaa1FXM25vY1dJK00ybEljU1AweFJRCkYxaUlvTWt4aHBsa0tNZ2M1empE
            eWY3S1RrZ1VsOEE4b1U1U3ZRemgzcGcKLS0tIDFHMDhWVkNqcDBON0JCaGd0VUdK
            c2FOd1NaQlk2YUllTE92MHlPbS9IaTQKAj32tqOkTmkFfaAoITmaRAyiNqX1/N8H
            PxNwThkmbjamCOB2QxBXpVnC+BlbAHye7ancZabyChA4zBL/CKvYMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:34:21Z"
    mac: ENC[AES256_GCM,data:ZwszQ4B98Ot5nV3E74xcjYPumllNkQuYbJ+z7S/vkOV9uRL5qSnG4aduAEsETBf5bbkn7CM0cy8w+tRmGIBjZ57SkXQx7ugfo6YfoqvTg6hDOBcJKatv2sfuD2a6N1KjOhkEaWKXwpXpnuKHu/lh5e5jhIalZGMyBq0C+RBAq5A=,iv:MW5QiQ0zx6IfIb5vnuizn54noRj4LijafisYv43xWPE=,tag:LU+HoucJw2w/EEHl5YrQZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
