app-template:
  controllers:
    prowlarr:
      containers:
        prowlarr:
          image:
            repository: ghcr.io/hotio/prowlarr
            tag: release-2.3.0.5236
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 10m
              memory: 192Mi
            limits:
              cpu: 200m
              memory: 384Mi

  service:
    prowlarr:
      controller: prowlarr
      ports:
        http:
          port: 9696

  ingress:
    prowlarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: prowlarr.hl.mathielo.com
          paths:
            - path: /
              service:
                identifier: prowlarr
                port: http
      tls:
        - hosts:
            - prowlarr.hl.mathielo.com
          secretName: prowlarr-hl-tls

  persistence:
    config:
      suffix: config
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path
      globalMounts:
        - path: /config
