app-template:
  controllers:
    prowlarr:
      containers:
        prowlarr:
          image:
            repository: ghcr.io/hotio/prowlarr
            tag: release-2.4.0.5397
          env:
            PUID: "1000"
            PGID: "1000"
            TZ: Europe/Stockholm
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

  service:
    prowlarr:
      controller: prowlarr
      ports:
        http:
          port: 9696

  ingress:
    prowlarr:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: prowlarr.m6o.dev
          paths:
            - path: /
              service:
                identifier: prowlarr
                port: http
      tls:
        - hosts:
            - prowlarr.m6o.dev
          secretName: prowlarr-tls

  persistence:
    config:
      existingClaim: prowlarr-config-lh
      globalMounts:
        - path: /config
